version: '3'

services: 
  file_server: 
    image: filebrowser/filebrowser
    restart: unless-stopped
    user: 197609:197121
    ports: 
      - 3001:80
    volumes:
      - ./data:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json